# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'featuresWindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FeaturesWindow(object):
    def setupUi(self, FeaturesWindow):
        FeaturesWindow.setObjectName("FeaturesWindow")
        FeaturesWindow.resize(257, 269)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(FeaturesWindow)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line = QtWidgets.QFrame(FeaturesWindow)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.checkBoxClipboardShortcut = QtWidgets.QCheckBox(FeaturesWindow)
        self.checkBoxClipboardShortcut.setObjectName("checkBoxClipboardShortcut")
        self.verticalLayout_2.addWidget(self.checkBoxClipboardShortcut)
        self.line_2 = QtWidgets.QFrame(FeaturesWindow)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.checkBoxWormholeTypeKeybind = QtWidgets.QCheckBox(FeaturesWindow)
        self.checkBoxWormholeTypeKeybind.setObjectName("checkBoxWormholeTypeKeybind")
        self.verticalLayout_2.addWidget(self.checkBoxWormholeTypeKeybind)
        self.line_3 = QtWidgets.QFrame(FeaturesWindow)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.checkBoxReminderBookmarkWormhole = QtWidgets.QCheckBox(FeaturesWindow)
        self.checkBoxReminderBookmarkWormhole.setObjectName("checkBoxReminderBookmarkWormhole")
        self.verticalLayout_2.addWidget(self.checkBoxReminderBookmarkWormhole)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(22, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBoxPlaySound = QtWidgets.QCheckBox(FeaturesWindow)
        self.checkBoxPlaySound.setObjectName("checkBoxPlaySound")
        self.verticalLayout.addWidget(self.checkBoxPlaySound)
        self.labelSndPath = QtWidgets.QLabel(FeaturesWindow)
        self.labelSndPath.setObjectName("labelSndPath")
        self.verticalLayout.addWidget(self.labelSndPath)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonTestSnd = QtWidgets.QPushButton(FeaturesWindow)
        self.pushButtonTestSnd.setObjectName("pushButtonTestSnd")
        self.horizontalLayout.addWidget(self.pushButtonTestSnd)
        self.pushButtonBrowseSnd = QtWidgets.QPushButton(FeaturesWindow)
        self.pushButtonBrowseSnd.setObjectName("pushButtonBrowseSnd")
        self.horizontalLayout.addWidget(self.pushButtonBrowseSnd)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.checkBoxFlashText = QtWidgets.QCheckBox(FeaturesWindow)
        self.checkBoxFlashText.setObjectName("checkBoxFlashText")
        self.verticalLayout.addWidget(self.checkBoxFlashText)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line_4 = QtWidgets.QFrame(FeaturesWindow)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.checkBoxSaveRefreshToken = QtWidgets.QCheckBox(FeaturesWindow)
        self.checkBoxSaveRefreshToken.setObjectName("checkBoxSaveRefreshToken")
        self.verticalLayout_2.addWidget(self.checkBoxSaveRefreshToken)
        self.buttonBox = QtWidgets.QDialogButtonBox(FeaturesWindow)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(FeaturesWindow)
        self.buttonBox.accepted.connect(FeaturesWindow.accept)
        self.buttonBox.rejected.connect(FeaturesWindow.reject)
        QtCore.QMetaObject.connectSlotsByName(FeaturesWindow)

    def retranslateUi(self, FeaturesWindow):
        _translate = QtCore.QCoreApplication.translate
        FeaturesWindow.setWindowTitle(_translate("FeaturesWindow", "Dialog"))
        self.checkBoxClipboardShortcut.setText(_translate("FeaturesWindow", "Clipboard EVE Praisal shortcut"))
        self.checkBoxWormholeTypeKeybind.setText(_translate("FeaturesWindow", "Wormhole type keybinds"))
        self.checkBoxReminderBookmarkWormhole.setText(_translate("FeaturesWindow", "Reminder to bookmark wormholes"))
        self.checkBoxPlaySound.setText(_translate("FeaturesWindow", "Play Sound"))
        self.labelSndPath.setText(_translate("FeaturesWindow", "PATH"))
        self.pushButtonTestSnd.setText(_translate("FeaturesWindow", "Play"))
        self.pushButtonBrowseSnd.setText(_translate("FeaturesWindow", "Browse"))
        self.checkBoxFlashText.setText(_translate("FeaturesWindow", "Flash Text"))
        self.checkBoxSaveRefreshToken.setText(_translate("FeaturesWindow", "Save CREST refresh token"))
